# fly.toml app configuration file for ShoutStream Player Generator
app = "shoutstream-player"
primary_region = "sjc"

[build]
  [build.command]
    description = "Build and install dependencies"
    entrypoint = "npm install && npm run build"

[env]
  PORT = "3100"
  NODE_ENV = "production"

[http_service]
  internal_port = 3100
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "15s"
  timeout = "10s"
  grace_period = "5s"
  method = "GET"
  path = "/"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
